### ISSUE TITLE
Merge audit findings into external

### ISSUE THREAD

**Issue by jjbailey-io** [thrackle-io/forte-rules-engine-v1#39]
Cherry-pick/Rebase/Merge the following findings into `external`: 

- [x]  TOB-THR-1 #85 
- [x]  TOB-THR-2 #45 
- [x]  TOB-THR-3 #48 
- [x]  TOB-THR-4 (OBE)
- [x]  TOB-THR-5 #40 
- [x]  TOB-THR-6 #62
- [x]  TOB-THR-7 #47 
- [x]  TOB-THR-8 #51
- [x]  TOB-THR-9 #46 
- [x]  TOB-THR-10 #44
- [x]  TOB-THR-11 (OBE)
- [x]  TOB-THR-12 #38
- [x]  TOB-THR-13 #49
- [x]  TOB-THR-14 #84 
- [x]  TOB-THR-15 #42
- [ ] TOB-THR-16 #52 
- [x] TOB-THR-17 #60
- [x] TOB-THR-18 #44 #73 
- [x] TOB-THR-19  #61  
- [ ] TOB-THR-20 
- [ ] TOB-THR-21 
- [x] TOB-THR-22 #93 
- [x] TOB-THR-23 #88 
- [x] TOB-THR-24 #96 
- [x] TOB-THR-25 #87 
- [ ] TOB-THR-26
- [ ] TOB-THR-27
- [x] TOB-THR-28 #86 
- [ ] Code Quality
- [ ] Documentation updates including the deployment guide changes required from removal of handler auto-deploy and #89 #95 
- [ ] Increment repository version #41

**Comment by jjbailey-io** [comment]
## Working Notes 
### All Issues
- [x]  TOB-THR-1 **external_023_squash** #23 
- [x]  TOB-THR-2  **external_024_squash** #24
- [x] TOB-THR-3 **external_025_squash**  #25 
- [ ] TOB-THR-4 (OBE)
- [x] TOB-THR-5 **external_027** #27 
- [x] TOB-THR-6 **external_028_squash** #28
- [x] TOB-THR-7 **external_029** #29
- [x] TOB-THR-8 **external_30_squash** #30
- [x] TOB-THR-9 **external_31_squash**  #31
- [x] TOB-THR-10 **external_032** #32
- [ ] TOB-THR-11 (OBE)
- [x] TOB-THR-12 **external_034** #34
- [x] TOB-THR-13 **external_035_squash** #35
- [x] TOB-THR-14 **external_036_squash** #36
- [x]  TOB-THR-15 **external_37** #37
- [x] TOB-THR-16 #52 
- [x] TOB-THR-17 **external_53** #53 
- [x] TOB-THR-18 **external_54** #54 
- [x] TOB-THR-19  **external_055_squash**  #55
- [x] TOB-THR-20 **external_075_squash** #75 
- [x] TOB-THR-21 **external_76_squash** #99 
- [x] TOB-THR-22 **external_077** #77 
- [x] TOB-THR-23 **external_078_squash** #78
- [x] TOB-THR-24 **external_079**  #79  
- [x] TOB-THR-25 **external_080_squash** #80
- [ ] ~TOB-THR-26~ - NOT FIXING FOR re-audit
- [ ] ~TOB-THR-27~ - NOT FIXING FOR re-audit
- [x] TOB-THR-28 **external_083_squash2** #83 
- [ ] Code Quality
- [ ] Documentation updates #89
- [ ] Increment repository version


###  ORDER OF COMMITS

1. external_027 - TOB-THR-05 - "Added setAppManagerAddress to protocolerc20"
2. external_029 - TOB-THR-07 - "Added script for deploying upgradeable NFT and its documentation"
3. external_30_squash TOB-THR-08 - "refactor _removeAddress logic and test"
4. external_31_squash - TOB-THR-09 - "Added zero checks"
5. external_032 - TOB-THR-10 - "Removed support for ERC721a"
6. external_034 - TOB-THR-12 - "Removed hasAccessLevel function"
7. external_035_squash - TOB-THR-13 - "Event emission refactor"
8. external_036_squash - TOB-THR-14 - "Refactor nft valaution logic and update unit tests"
9. external_53 - TOB-THR-17 - "updated rule check logic and tests"
10. external_055_squash - TOB-THR-19 - "Added testing for accessLevel0 and refactored logic"
11. external_023_squash (conflicts resolved) - TOB-THR-01 - "Consolidated logic for all period date based rules"
12. external_024_squash (conflicts resolved) - TOB-THR-02 - "Added the audit requested events"
13. external_028_squash (conflicts resolved) - TOB-THR-06 - "Added 2-step verifification for critical operations"
14. external_37 (resolved conflicts) - TOB-THR-15 - "Removed Fee data from ERC721Handler"
15. external_054 (resolved conflicts) - TOB-THR-18 - "Added error for batch mint and burn with the tests and documentation"
16. external_025_squash (resolved conflicts) - TOB-THR-03 - "Added owner to all ERC20 stuff"
17. external_077 - TOB-THR-22 - "Removed percentage rule checks since they are not in this release"
18. external_079 - TOB-THR-24 - "All changes to address audit 24"
19. external_078_squash - TOB-THR-23 - "Added custom errors to rule getters when the rule does not exist"
20. external_083_squash2 - TOB-THR-28 - "Refactored dataModule contract to set the AppManager address"
21. external_080_squash - TOB-THR-25 - "Made changes for rule validation"
22. external_075_squash - TOB-THR-20 - "Updated to use Rule Admin role and logic"
23. external_76_squash - TOB-THR-21 - "Updated rules to account for burns"
24. external_52_squash - TOB-THR-16 - "safeMint access modifier defaulted to app administrator or owner"

**Comment by jjbailey-io** [comment]
1. TOB-THR-1 - Starting time for rule activation is stored incorrectly - https://github.com/thrackle-io/rules-protocol/commit/608a18e87d1f01e620f88d681d32246d9bb2c641
2. TOB-THR-2 - Insufficient event generation - https://github.com/thrackle-io/rules-protocol/commit/99cd76a8fed035b3385ef700e851d345008c0ed4
3. TOB-THR-3 - Missing access control in handlers - https://github.com/thrackle-io/rules-protocol/commit/a4a91d2ba961e37eaab8b19a60d92ab55f37ef56
4. TOB-THR-4 - Ineffective access control checks in Facets - NO CHANGES
5. TOB-THR-5 - AppManager cannot be updated in ProtocolERC20 - https://github.com/thrackle-io/rules-protocol/commit/646bc8f7954205cee5eb76af4542862c36a9029a
6. TOB-THR-6 - Lack of two-step process for critical operations - https://github.com/thrackle-io/rules-protocol/commit/78234aae2ca50e34eba95a78819f6d8e81860194
7. TOB-THR-7 - Initialization function is vulnerable to front-running - https://github.com/thrackle-io/rules-protocol/commit/ea63bcc75a1fb96270ef50cdfdf021d027af6721
8. TOB-THR-8 - Incorrect implementation of _removeAddress function - https://github.com/thrackle-io/rules-protocol/commit/1fa9584c15cbb1ab2cbf215482e9b5a683070f32
9. TOB-THR-9 - Lack of zero-value checks in setter functions - https://github.com/thrackle-io/rules-protocol/commit/578ac7f1a76016d36c90bfbf205716cd887902c8
10. TOB-THR-10 - ProtocolERC721A prices cannot be fetched - https://github.com/thrackle-io/rules-protocol/commit/83d275a75df3127a2e5a5dbcd155a3c6e735cfab
11. TOB-THR-11 - Lack of contract existence checks in external calls - NO CHANGES
12. TOB-THR-12 - Incorrect access level info returned - https://github.com/thrackle-io/rules-protocol/commit/ee80df27da9b77b010ef430cd5430843d50517de
13. TOB-THR-13 - Improper event emission - https://github.com/thrackle-io/rules-protocol/commit/7df24a48321c35df9378cdc72cc09e914f1ca375
14. TOB-THR-14 - Unbounded loop in getAccTotalValuation could result in denial of service - https://github.com/thrackle-io/rules-protocol/commit/0514720b1affcf99df1141c5075a66b5fb2d9e53
15. TOB-THR-15 - Fee contract never set in ProtocolERC721Handler - https://github.com/thrackle-io/rules-protocol/commit/6209733a847edc0131acaf4000cdbc2c8460dd49
16. TOB-THR-16 - Missing validation in publicly callable safeMint - https://github.com/thrackle-io/rules-protocol/commit/9e0f37473fd5ec83cb77df81b5fd1f16396e18ec
17. TOB-THR-17 - Inconsistent implementation of risk processing - https://github.com/thrackle-io/rules-protocol/commit/53bc8af0e85ae5ff3953840e665533342e96336b
18. TOB-THR-18 - Batch minting breaks ProtocolERC721Handler rule handling - https://github.com/thrackle-io/rules-protocol/commit/0467b8e1ab638520bed10d29f91a1eeb0dad7f74
19. TOB-THR-19 - Access level zero rule checks can be bypassed - https://github.com/thrackle-io/rules-protocol/commit/a6d5b0092c846e3857edf48f0d81467158c26272
20. TOB-THR-20 - App administrator is a single point of failure - https://github.com/thrackle-io/rules-protocol/commit/5571e1e79079566a7ed944d1517badf1bf4fd36b
21. TOB-THR-21 - Application rules can unintentionally prevent token burning - https://github.com/thrackle-io/rules-protocol/commit/089ebb7ee46654d46b98ea10bca317ac8336d051
22. TOB-THR-22 - Percentage rules can be bypassed - https://github.com/thrackle-io/rules-protocol/commit/10b8b11a9ba44659fd3e8e98e4b5f44809e0aadb
23. TOB-THR-23 - Multiple functions return an empty rule instead of reverting - https://github.com/thrackle-io/rules-protocol/commit/64b04fe788f38fd26741261cc6a84e1819ece3ad
24. TOB-THR-24 - App administrator can bypass the admin withdrawal rule - https://github.com/thrackle-io/rules-protocol/commit/9553a805deca780e4136c6cec811f1e15e63fa58
25. TOB-THR-25 - RuleDataFacet functions and data structures are misconfigured - https://github.com/thrackle-io/rules-protocol/commit/8f086e8ee2043d4fa4006d0491dc820e6b0475f7
26. TOB-THR-26 - Token transfers can revert due to transfer fees exceeding the transfer amount - NO CHANGES
27. TOB-THR-27 - Pre-image of storage slots is known - NO CHANGES
28. TOB-THR-28 - dataModuleAppManagerAddress can’t be set in DataModule contract - https://github.com/thrackle-io/rules-protocol/commit/6f53bba6e498f1f7b3d3829955fec514ab10628e
